### ISSUE TITLE
crash with git from today

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#279]
I had one crash today, it did run without log in daemon mode
command line was "minisatip -D5 -o 192.168.178.1:2000  -Y 0:dvbc2,1:dvbc2,2:dvbc,3:dvbc,8:dvbt  -m 0040caa20000 -t"
```
Mar  9 22:35:51 satip systemd[1]: Started Multi-threaded SAT>IP server.
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: Setting delivery system for adapter 0 to dvbc2 and dvbc
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: Setting delivery system for adapter 1 to dvbc2 and dvbc
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: Setting delivery system for adapter 2 to dvbc and undefined
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: Setting delivery system for adapter 3 to dvbc and undefined
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: Setting delivery system for adapter 8 to dvbt and undefined
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.214 main]: minisatip version 0.5.34, compiled with s2api version: 050A
Mar  9 22:35:51 satip minisatip[12904]: [09/03 22:35:51.287 main]: Initializing with 9 devices
Mar  9 22:37:32 satip systemd[1]: Time has been changed
Mar  9 22:37:32 satip systemd[1034]: Time has been changed
Mar  9 22:40:46 satip minisatip[12904]: *** stack smashing detected ***: /usr/bin/minisatip terminated
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.489 main]: RECEIVED SIGNAL 6 - SP=0 IP=0
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.490 main]: Obtained 10 stack frames.
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.490 main]: 0x4165e8 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x4165e8': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.494 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.494 main]: 0x416730 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x416730': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.500 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.500 main]: 0x7fa06066cd10 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa06066cd10': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.504 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.504 main]: 0x7fa05f87f267 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f87f267': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.508 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.508 main]: 0x7fa05f880eca :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f880eca': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.512 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.513 main]: 0x7fa05f8c2bf3 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f8c2bf3': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.517 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.517 main]: 0x7fa05f962e3c :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f962e3c': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.522 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.522 main]: 0x7fa05f962de0 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f962de0': No such file
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x7fa05f962de0': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.527 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.527 main]: 0x417ba2 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x417ba2': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.531 main]:
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.531 main]: 0x417d69 :
Mar  9 22:40:46 satip minisatip[12904]: addr2line: '0x417d69': No such file
Mar  9 22:40:46 satip minisatip[12904]: [09/03 22:40:46.535 main]:
Mar  9 22:40:46 satip systemd[1]: minisatip.service: Main process exited, code=exited, status=1/FAILURE
Mar  9 22:40:46 satip systemd[1]: minisatip.service: Unit entered failed state.
Mar  9 22:40:46 satip systemd[1]: minisatip.service: Failed with result 'exit-code'.
```

**Comment by catalinii** [comment]
Hi,

can u please try to reporduce with the commit from today ? I could not get the exact error line.

If you can also start it with gdb --args ./minisatip

and if it is inside of snprintf_pointer you can do
print (char *)a
print *(char **)a

up  - until you are in var_eval
print var


Thanks

**Comment by 9000h** [comment]
ok will try,  did also try yesterday but was not able to reproduce it

**Comment by 9000h** [comment]
ok got it again
```
Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff45a3700 (LWP 20299)]
0x00007ffff6ea611d in writev () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff6ea611d in writev () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000040c5b7 in my_writev (sock=16, iov=0x6822e0, iiov=7,
    sid=0x681750) at stream.c:539
#2  0x000000000040d6fe in flush_streami (sid=0x681750, ctime=408816)
    at stream.c:764
#3  0x000000000040daaf in process_packet (
    b=0x667588 "G\a\201\033\214\247\264\214bj\276\245Z\276\310<\224\355\253v\205\227\066mG\343\222w\237m\nH\220\214\210\351|?\341F\025\351㻗\342|\206\312{H\306&\253\352M\253\321y\031l\332rh\332\017\224\270v\202\r\320q\332l=MF@",
    ad=0x644a40) at stream.c:852
#4  0x000000000040dc0a in process_dmx (s=0x6734f0) at stream.c:900
#5  0x000000000040e191 in read_dmx (s=0x6734f0) at stream.c:1001
#6  0x00000000004095df in select_and_execute (arg=0x645830)
    at socketworks.c:643
#7  0x00007ffff7bc26aa in start_thread (arg=0x7ffff45a3700)
    at pthread_create.c:333
#8  0x00007ffff6eafe9d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
(gdb) thread apply all bt full

Thread 14 (Thread 0x7ffff45a3700 (LWP 20299)):
#0  0x00007ffff6ea611d in writev () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x000000000040c5b7 in my_writev (sock=16, iov=0x6822e0, iiov=7,
    sid=0x681750) at stream.c:539
        rv = -1
        ra = "\000\000\000\006\000\000\002\000\001\000\000\006\000\000\001\000\0                                                                                                                                60\t\001\344\377\177\000\000\300\b\000\344\377\177\000\000 \317f\000\000\000\000                                                                                                                                \000\020\307A \000\000\000\000\220 "
        log_level = 7
        stime = 0
#2  0x000000000040d6fe in flush_streami (sid=0x681750, ctime=408816)
    at stream.c:764
        rv = 1
#3  0x000000000040daaf in process_packet (
    b=0x667588 "G\a\201\033\214\247\264\214bj\276\245Z\276\310<\224\355\253v\205                                                                                                                                \227\066mG\343\222w\237m\nH\220\214\210\351|?\341F\025\351㻗\342|\206\312{H\306&                                                                                                                                \253\352M\253\321y\031l\332rh\332\017\224\270v\202\r\320q\332l=MF@",
    ad=0x644a40) at stream.c:852
        j = 0
        cc = 11
        p = 0x644bd8
---Type <return> to continue, or q <return> to quit---
        _pid = 1921
        sid = 0x681750
        rtime = 408816
#4  0x000000000040dc0a in process_dmx (s=0x6734f0) at stream.c:900
        min = 0x100000064
        max = 0x644a40
        i = 0
        j = 0
        dp = 1880
        cnt = 0
        sid = 0x42dec8
        ad = 0x644a40
        send = 0
        flush_all = 0
        stime = 478211541180
        rlen = 25004
        ms_ago = 24
#5  0x000000000040e191 in read_dmx (s=0x6734f0) at stream.c:1001
        cnt = 1
        ad = 0x644a40
        send = 1
        flush_all = 0
        ls = 1
        lse = 0
#6  0x00000000004095df in select_and_execute (arg=0x645830) at socketworks.c:643
        ss = 0x6734f0
        io = {__fds_bits = {4294967295 <repeats 12 times>, 17179869182, 844437815033874, 4294967295, 4294967295}}
        i = 13
        rv = 1
        rlen = 12972
        les = 2
        es = 2
        buf = '\000' <repeats 1976 times>...
        err = 0
        pf = {{fd = -1, events = 0, revents = 0} <repeats 12 times>, {fd = -2, events = 3, revents = 0}, {fd = 18, events = 3, revents = 3}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0,
            revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -2, events = 3, revents = 0}, {fd = 0, events = 0, revents = 0} <repeats 81 times>}
        lt = 408628
        c_time = 408816
        read_ok = 1
        ra = '\000' <repeats 49 times>
#7  0x00007ffff7bc26aa in start_thread (arg=0x7ffff45a3700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffff45a3700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737292941056, 2099275624726251321, 0, 140737488337455, 8388608, 6712864, -2099301147105704135, -2099293742792194247}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007ffff6eafe9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 13 (Thread 0x7ffff2da0700 (LWP 20294)):
#0  0x00007ffff6ea488d in poll () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x0000000000408f2d in select_and_execute (arg=0x6449e0) at socketworks.c:557
        io = {__fds_bits = {4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 17179869182, 4294967295, 12884901899, 4294967295, 4294967295, 4294967295,
            4294967295, 4294967295}}
---Type <return> to continue, or q <return> to quit---
        i = -1
        rv = 1
        rlen = 4324
        les = 2
        es = 2
        buf = '\000' <repeats 1976 times>...
        err = 0
        pf = {{fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1,
            events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -2, events = 3, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = 11, events = 3,
            revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {
            fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0} <repeats 81 times>}
        lt = 408688
        c_time = 408794
        read_ok = 1
        ra = '\000' <repeats 49 times>
#2  0x00007ffff7bc26aa in start_thread (arg=0x7ffff2da0700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffff2da0700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737267762944, 2099275624726251321, 0, 140737488340863, 8388608, 6790432, -2099304435440040135, -2099293742792194247}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff6eafe9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.

Thread 2 (Thread 0x7ffff6da8700 (LWP 19899)):
#0  0x00007ffff6ea488d in poll () at ../sysdeps/unix/syscall-template.S:81
No locals.
#1  0x0000000000408f2d in select_and_execute (arg=0x42cd8d) at socketworks.c:557
        io = {__fds_bits = {4294967295, 4294967295, 4294967295, 4294967295, 17179869182, 17179869182, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295, 4294967295,
            4294967295, 4294967295}}
        i = -1
        rv = 0
        rlen = 0
        les = 2
        es = 2
        buf = '\000' <repeats 1240 times>...
        err = 0
        pf = {{fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -2, events = 3, revents = 0}, {fd = -2,
            events = 3, revents = 0}, {fd = -1, events = 0, revents = 0} <repeats 13 times>, {fd = 0, events = 0, revents = 0} <repeats 81 times>}
        lt = 408684
        c_time = 408806
        read_ok = 0
        ra = '\000' <repeats 49 times>
#2  0x00007ffff7bc26aa in start_thread (arg=0x7ffff6da8700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffff6da8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737334904576, 2099275624726251321, 0, 140737488347871, 140737334905280, 0, -2099295652231919815, -2099293742792194247}, mask_was_saved = 0}}, priv = {
            pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff6eafe9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
---Type <return> to continue, or q <return> to quit---
No locals.

Thread 1 (Thread 0x7ffff7fcd8c0 (LWP 19895)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
No locals.
#1  0x00007ffff7bc4d82 in __GI___pthread_mutex_lock (mutex=0x681760) at ../nptl/pthread_mutex_lock.c:115
        id = -138630307
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = 1
        id = <optimized out>
#2  0x00000000004188a2 in mutex_lock1 (FILE=0x42d405 "socketworks.c", line=371, mutex=0x681758) at utils.c:939
        rv = 0
        start_lock = 408816
#3  0x0000000000408442 in sockets_lock (ss=0x666af0) at socketworks.c:371
No locals.
#4  0x000000000040908e in select_and_execute (arg=0x0) at socketworks.c:577
        ss = 0x666af0
        io = {__fds_bits = {12884901891, 12884901892, 12884901893, 12884901894, 4294967295, 4294967295, 17179869182, 12884901895, 4294967295, 12884901897, 4294967295, 7036887302668304, 4294967295,
            4294967295, 4294967295, 4294967295}}
        i = 11
        rv = 1
        rlen = 48
        les = 9
        es = 9
        buf = "\201\311\000\a\031I]\000\031I\\\377\000\000\000\000\000\000OI\000\000\000\000\000\000\000\006\000\000\r\223\201\312\000\003\031I]\000\001\005satip\000\000\000\000User-Agent:\000Lavf56.40.101\000\000Session:\000\060\064\062\064\062\063\070\063\063\065\000\000\000\n\000\066_64;\000rv:45.0)\000Gecko/20100101\000Firefox/45.0\000\000Accept:\000image/png,image/*;q=0.8,*/*;q=0.5\000\000Accept-Lang"...
        err = 0
        pf = {{fd = 3, events = 3, revents = 0}, {fd = 4, events = 3, revents = 0}, {fd = 5, events = 3, revents = 0}, {fd = 6, events = 3, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1,
            events = 0, revents = 0}, {fd = -2, events = 3, revents = 0}, {fd = 7, events = 3, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = 9, events = 3, revents = 0}, {fd = -1, events = 0,
            revents = 0}, {fd = 16, events = 3, revents = 25}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0},
          {fd = 25, events = 3, revents = 0}, {fd = 26, events = 3, revents = 25}, {fd = -1, events = 0, revents = 0}, {fd = 4381959, events = 0, revents = 0}, {fd = -151813566, events = 32767,
            revents = 0}, {fd = -8496, events = 32767, revents = 0}, {fd = -8184, events = 32767, revents = 0}, {fd = -151813577, events = 32767, revents = 0}, {fd = 0, events = 0, revents = 0}, {
            fd = -153131218, events = 32767, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = -9632, events = 32767, revents = 0}, {fd = 4389505, events = 0, revents = 0}, {fd = -8432, events = 0,
            revents = 0}, {fd = -8056, events = 0, revents = 0}, {fd = -1, events = -1, revents = -1}, {fd = -8056, events = 32767, revents = 0}, {fd = 0, events = 32767, revents = 0}, {fd = 0, events = 0,
            revents = 0}, {fd = -9568, events = 32767, revents = 0}, {fd = 0, events = -1, revents = -1}, {fd = 0, events = 0, revents = 0}, {fd = 1, events = 0, revents = 0}, {fd = 0, events = 0,
            revents = 0}, {fd = -8272, events = 32767, revents = 0}, {fd = -151789728, events = 32767, revents = 0}, {fd = -7912, events = 32767, revents = 0}, {fd = -152988768, events = 32767,
            revents = 0}, {fd = 4394082, events = 0, revents = 0}, {fd = -8304, events = 32767, revents = 0}, {fd = 4381988, events = 0, revents = 0}, {fd = -8288, events = 32767, revents = 0}, {fd = -7912,
            events = 32767, revents = 0}, {fd = 4381959, events = 0, revents = 0}, {fd = -7912, events = 32767, revents = 0}, {fd = -153131218, events = 32767, revents = 0}, {fd = -153140461,
            events = 32767, revents = 0}, {fd = -9424, events = 32767, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = -1, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = -3,
            events = -1, revents = -1}, {fd = 4389505, events = 0, revents = 0}, {fd = -8192, events = 32767, revents = 0}, {fd = -7816, events = 32767, revents = 0}, {fd = 4389500, events = 0,
            revents = 0}, {fd = -7816, events = 32767, revents = 0}, {fd = -153131218, events = 32767, revents = 0}, {fd = 48, events = 0, revents = 0}, {fd = -9328, events = 32767, revents = 0}, {fd = 0,
            events = 32767, revents = 0}, {fd = 10, events = 0, revents = 0}, {fd = -8361, events = 0, revents = 0}, {fd = 0, events = 32767, revents = 0}, {fd = -8347, events = 32767, revents = 0}, {
            fd = 0, events = 0, revents = 0}, {fd = 0, events = 32767, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = 100, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0}, {
            fd = -153140448, events = 0, revents = 0}, {fd = 0, events = 5, revents = 0}, {fd = 0, events = 32767, revents = 0}, {fd = -9376, events = 32767, revents = 0}, {fd = -1, events = -1,
            revents = -1}, {fd = 3, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = 5, events = 22, revents = 0}, {fd = 0, events = 0, revents = 0}, {fd = 0, events = 0, revents = 0}, {
            fd = 4378066, events = 0, revents = 0}, {fd = -7968, events = 32767, revents = 0}, {fd = -7544, events = 32767, revents = 0}, {fd = 4378046, events = 0, revents = 0}, {fd = -7544,
            events = 32767, revents = 0}, {fd = -153131218, events = 32767, revents = 0}, {fd = -1, events = -1, revents = -1}, {fd = -9104, events = 32767, revents = 0}, {fd = 4398629, events = 0,
            revents = 0}, {fd = 16, events = 0, revents = 0}, {fd = 4389501, events = 0, revents = 0}, {fd = -1, events = -1, revents = -1}, {fd = -7696, events = 32767, revents = 0}, {fd = 0, events = 27,
            revents = 0}}
        lt = 408717
        c_time = 408816
        read_ok = 1
        ra = "192.168.178.129\000\033\354B\000\000\000\000\000\000\000\000\000\002\000\000\000`\314B\000\000\000\000\000\000\020\000\000\000\000\000\000\060\002"
#5  0x0000000000406d38 in main (argc=9, argv=0x7fffffffe4a8) at minisatip.c:1213
        sock_bw = 5
(gdb)
(gdb) print *(char *)a
$5 = 16 '\020'
(gdb) print (char )a
$6 = 32 ' '
(gdb)
```

**Comment by catalinii** [comment]
Hi,
you caught SIGPIPE

try 
handle SIGPIPE nostop noprint pass
before starting minisatip.

Also do:

print (char **)p
print *(char ****)a

**Comment by catalinii** [comment]
print (char  \*)a
print \*(char \*\*)a

**Comment by 9000h** [comment]
it's hard to reproduce

**Comment by 9000h** [comment]
looks like it has something todo with the status page
```
root@satip:/usr/src/satip/minisatip# gdb --args /usr/bin/minisatip -f -D5 -o 192.168.178.1:2000  -Y 0:dvbc2,1:dvbc2,2:dvbc,3:dvbc,8:dvbt  -m 0040caa2c79d
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/minisatip...done.
(gdb) set filename-display absolute
(gdb) handle SIGPIPE nostop noprint pass
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
(gdb) r
Starting program: /usr/bin/minisatip -f -D5 -o 192.168.178.1:2000 -Y 0:dvbc2,1:dvbc2,2:dvbc,3:dvbc,8:dvbt -m 0040caa2c79d
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[10/03 22:23:00.608 main]: Setting delivery system for adapter 0 to dvbc2 and dvbc
[10/03 22:23:00.608 main]: Setting delivery system for adapter 1 to dvbc2 and dvbc
[10/03 22:23:00.609 main]: Setting delivery system for adapter 2 to dvbc and undefined
[10/03 22:23:00.609 main]: Setting delivery system for adapter 3 to dvbc and undefined
[10/03 22:23:00.609 main]: Setting delivery system for adapter 8 to dvbt and undefined
[10/03 22:23:00.609 main]: minisatip version 0.5.35, compiled with s2api version: 050A
[New Thread 0x7ffff6da8700 (LWP 29836)]
[New Thread 0x7ffff65a7700 (LWP 29838)]
[New Thread 0x7ffff5da6700 (LWP 29840)]
[New Thread 0x7ffff55a5700 (LWP 29842)]
[New Thread 0x7ffff4da4700 (LWP 29844)]
[New Thread 0x7ffff45a3700 (LWP 29846)]
[New Thread 0x7ffff3da2700 (LWP 29848)]
[New Thread 0x7ffff35a1700 (LWP 29850)]
[New Thread 0x7ffff2da0700 (LWP 29852)]
[New Thread 0x7ffff259f700 (LWP 29854)]
[10/03 22:23:00.707 main]: Initializing with 9 devices
[Thread 0x7ffff4da4700 (LWP 29844) exited]
[Thread 0x7ffff5da6700 (LWP 29840) exited]
[Thread 0x7ffff55a5700 (LWP 29842) exited]
[Thread 0x7ffff35a1700 (LWP 29850) exited]
[Thread 0x7ffff65a7700 (LWP 29838) exited]
[Thread 0x7ffff259f700 (LWP 29854) exited]
[Thread 0x7ffff2da0700 (LWP 29852) exited]
*** stack smashing detected ***: /usr/bin/minisatip terminated

Program received signal SIGABRT, Aborted.
0x00007ffff6dde267 in __GI_raise (sig=sig@entry=6)
    at /build/glibc-ryFjv0/glibc-2.21/signal/../sysdeps/unix/sysv/linux/raise.c:55
55	/build/glibc-ryFjv0/glibc-2.21/signal/../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) thread apply all bt

Thread 8 (Thread 0x7ffff3da2700 (LWP 29848)):
#0  0x00007ffff6ea488d in poll ()
    at /build/glibc-ryFjv0/glibc-2.21/io/../sysdeps/unix/syscall-template.S:81
#1  0x0000000000408f2d in select_and_execute (arg=0x645830)
    at /usr/src/satip/minisatip/socketworks.c:557
#2  0x00007ffff7bc26aa in start_thread (arg=0x7ffff3da2700)
    at /build/glibc-ryFjv0/glibc-2.21/nptl/pthread_create.c:333
#3  0x00007ffff6eafe9d in clone ()
    at /build/glibc-ryFjv0/glibc-2.21/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7ffff45a3700 (LWP 29846)):
#0  0x00007ffff6ea488d in poll ()
    at /build/glibc-ryFjv0/glibc-2.21/io/../sysdeps/unix/syscall-template.S:81
#1  0x0000000000408f2d in select_and_execute (arg=0x6449e0)
    at /usr/src/satip/minisatip/socketworks.c:557
#2  0x00007ffff7bc26aa in start_thread (arg=0x7ffff45a3700)
---Type <return> to continue, or q <return> to quit--- 
    at /build/glibc-ryFjv0/glibc-2.21/nptl/pthread_create.c:333
#3  0x00007ffff6eafe9d in clone ()
    at /build/glibc-ryFjv0/glibc-2.21/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7ffff6da8700 (LWP 29836)):
#0  0x00007ffff6ea488d in poll ()
    at /build/glibc-ryFjv0/glibc-2.21/io/../sysdeps/unix/syscall-template.S:81
#1  0x0000000000408f2d in select_and_execute (arg=0x42cd8d)
    at /usr/src/satip/minisatip/socketworks.c:557
#2  0x00007ffff7bc26aa in start_thread (arg=0x7ffff6da8700)
    at /build/glibc-ryFjv0/glibc-2.21/nptl/pthread_create.c:333
#3  0x00007ffff6eafe9d in clone ()
    at /build/glibc-ryFjv0/glibc-2.21/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fcd8c0 (LWP 29832)):
#0  0x00007ffff6dde267 in __GI_raise (sig=sig@entry=6)
    at /build/glibc-ryFjv0/glibc-2.21/signal/../sysdeps/unix/sysv/linux/rais---Type <return> to continue, or q <return> to quit---
e.c:55
#1  0x00007ffff6ddfeca in __GI_abort ()
    at /build/glibc-ryFjv0/glibc-2.21/stdlib/abort.c:89
#2  0x00007ffff6e21bf3 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff6f37d6d "*** %s ***: %s terminated\n")
    at /build/glibc-ryFjv0/glibc-2.21/libio/../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6ec1e3c in __GI___fortify_fail (msg=<optimized out>, 
    msg@entry=0x7ffff6f37d55 "stack smashing detected")
    at /build/glibc-ryFjv0/glibc-2.21/debug/fortify_fail.c:38
#4  0x00007ffff6ec1de0 in __stack_chk_fail ()
    at /build/glibc-ryFjv0/glibc-2.21/debug/stack_chk_fail.c:28
#5  0x0000000000417be5 in var_eval (
    orig=0x7ffff7ff2371 "$ad_pids5$\", \"$ad_pids6$\", \"$ad_pids7$\", \"$ad_pids8$\", \"$ad_pids9$\", \"$ad_pids10$\", \"$ad_pids11$\", \"$ad_pids12$\", \"$ad_pids13$\", \"$ad_pids14$\", \"$ad_pids15$\" ];\nvar ad_satip\t= [\"$ad_satip0$\", \"$ad_sat"..., len=9, 
    dest=0x7fffffffb427 "255,18,259,32,4103,4101,48,4104,4128,96,600,4099,0,1,16,261,7372,6604,7884,6860,7116,8140,20,17,262", max_len=5613)
    at /usr/src/satip/minisatip/utils.c:771
---Type <return> to continue, or q <return> to quit---
#6  0x0000000000417dac in process_file (
    sock=<error reading variable: Cannot access memory at address 0x7fff00001194>, 
    s=<error reading variable: Cannot access memory at address 0x7fff0000118c>, 
    len=<error reading variable: Cannot access memory at address 0x7fff00001188>, 
    ctype=<error reading variable: Cannot access memory at address 0x7fff0000117c>) at /usr/src/satip/minisatip/utils.c:807
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
(gdb) print (char )p
No symbol "p" in current context.
(gdb) print (char *)a
$1 = 0x63aa20 <a> "\020\340c"
(gdb) print (char *)a
$2 = 0x63aa20 <a> "\020\340c"
(gdb) print *(char **)a
$3 = 0x63e010 ""
(gdb) print sock
$4 = 25
(gdb) print (char *)sock
$5 = 0x19 <error: Cannot access memory at address 0x19>
(gdb) print s
$6 = {0x63ef40, 0x643400, 0x6434f0, 0x6435e0, 0x6436d0, 0x643a10, 0x643b00, 0x64d6f0, 0x653bf0, 0x65a0f0, 0x6605f0, 0x666af0, 0x66cff0, 0x6734f0, 0x6799f0, 0x67fef0, 0x680230, 
  0x680320, 0x681070, 0x681160, 0x681250, 0x681fa0, 0x682090, 0x0 <repeats 77 times>}
(gdb) print (char *)s
$7 = 0x639c80 <s> "@\357c"
(gdb) print (char **)s
$8 = (char **) 0x639c80 <s>

``

**Comment by catalinii** [comment]
I think it should be fine now, can you check ?

Thanks

**Comment by 9000h** [comment]
fixed
