### ISSUE TITLE
crash with git from today 04.04.2016

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#296]
I have a crash here on dvb-t with bad/no signal from the antenna
```
root@satip:/usr/src/satip/minisatip# gdb --args /usr/bin/minisatip -f -D5 -o 192.168.178.1:2000  -Y 0:dvbc2,1:dvbc2,2:dvbc,3:dvbc,8:dvbt  -m 0040caa2c79d
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/minisatip...done.
(gdb) set filename-display absolute
(gdb) thread apply all bt
(gdb) handle SIGPIPE nostop noprint pass
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
(gdb) r
Starting program: /usr/bin/minisatip -f -D5 -o 192.168.178.1:2000 -Y 0:dvbc2,1:dvbc2,2:dvbc,3:dvbc,8:dvbt -m 0040caa2c79d
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[04/04 16:42:46.045 main]: Setting delivery system for adapter 0 to dvbc2 and dvbc
[04/04 16:42:46.045 main]: Setting delivery system for adapter 1 to dvbc2 and dvbc
[04/04 16:42:46.045 main]: Setting delivery system for adapter 2 to dvbc and undefined
[04/04 16:42:46.045 main]: Setting delivery system for adapter 3 to dvbc and undefined
[04/04 16:42:46.045 main]: Setting delivery system for adapter 8 to dvbt and undefined
[04/04 16:42:46.046 main]: minisatip version 0.5.45, compiled with s2api version: 050A
[04/04 16:42:46.046 main]: Built with dvbcsa
[04/04 16:42:46.046 main]: Built with CI
[04/04 16:42:46.046 main]: Built with dvbapi
[04/04 16:42:46.046 main]: Built with AES (OpenSSL)
[04/04 16:42:46.046 main]: Built with tables processing
[04/04 16:42:46.046 main]: Built with satip client
[04/04 16:42:46.046 main]: Built with linux dvb client
[04/04 16:42:46.046 main]: Built with backtrace
[04/04 16:42:46.046 main]: Built without netceiver
[New Thread 0x7ffff6760700 (LWP 29465)]
[New Thread 0x7ffff5f5f700 (LWP 29467)]
[New Thread 0x7ffff575e700 (LWP 29469)]
[New Thread 0x7ffff4f5d700 (LWP 29471)]
[New Thread 0x7ffff475c700 (LWP 29473)]
[New Thread 0x7ffff3f5b700 (LWP 29475)]
[New Thread 0x7ffff375a700 (LWP 29477)]
[New Thread 0x7ffff2f59700 (LWP 29479)]
[New Thread 0x7ffff2758700 (LWP 29481)]
[04/04 16:42:46.137 main]: Initializing with 8 devices
[Thread 0x7ffff4f5d700 (LWP 29471) exited]
[Thread 0x7ffff475c700 (LWP 29473) exited]
[Thread 0x7ffff575e700 (LWP 29469) exited]
[Thread 0x7ffff5f5f700 (LWP 29467) exited]
[Thread 0x7ffff375a700 (LWP 29477) exited]
[Thread 0x7ffff2f59700 (LWP 29479) exited]
[Thread 0x7ffff2758700 (LWP 29481) exited]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000040fbef in init_hw (i=8) at /usr/src/satip/minisatip/adapter.c:191
#2  0x000000000041136e in get_free_adapter (freq=578000, pol=0, msys=3, src=-1, diseqc=1) at /usr/src/satip/minisatip/adapter.c:515
#3  0x000000000040b731 in start_play (sid=0x67b0a0, s=0x64e7e0) at /usr/src/satip/minisatip/stream.c:256
#4  0x0000000000404b74 in read_rtsp (s=0x64e7e0) at /usr/src/satip/minisatip/minisatip.c:791
#5  0x00000000004097f4 in select_and_execute (arg=0x0) at /usr/src/satip/minisatip/socketworks.c:645
#6  0x0000000000406ee8 in main (argc=9, argv=0x7fffffffe488) at /usr/src/satip/minisatip/minisatip.c:1281
(gdb)
(gdb) print (char )p
No symbol "p" in current context.
(gdb) print (char *)a
$1 = 0x63b720 <a> "\020\360c"
(gdb) print *(char **)a
$2 = 0x63f010 ""
(gdb) print (char *)s
$3 = 0x63aec0 <s> "P\377c"
(gdb) print s
$4 = {0x63ff50, 0x644450, 0x644550, 0x644650, 0x644750, 0x644aa0, 0x644ba0, 0x64e7e0, 0x654cf0, 0x65b200, 0x661710, 0x667c20, 
  0x66e130, 0x674640, 0x67ab50, 0x67aea0, 0x67afa0, 0x67bd10, 0x67be10, 0x67db30, 0x0 <repeats 80 times>}
(gdb) 
```

**Comment by catalinii** [comment]
Hi, try with the latest commit.

**Comment by 9000h** [comment]
looks like it's fixed
