### ISSUE TITLE
crash with ddci and latest git

### ISSUE THREAD

**Issue by grisia** [catalinii/minisatip#762]
When compiling latest git version (v1.0.4-849c135) with 'DDCI=1' minisatip will crash.

I'm on arch linux with kernel version 5.8.7.
I have two Digital Devices adapters one 'Devices MAX S8 4/8' and one 'Digital Devices Octopus Mini' with CI attached.

When switching to a scrambled channel minisatip will crash.

### Kernel ddbridge module init

```
# dmesg | grep ddbridge
ddbridge: Digital Devices PCIE bridge driver 0.9.33-integrated, Copyright (C) 2010-17 Digital Devices GmbH
ddbridge 0000:01:00.0: enabling device (0000 -> 0002)
ddbridge 0000:01:00.0: detected Digital Devices MAX S8 4/8
ddbridge 0000:01:00.0: HW 0201000f REGMAP 00010002
ddbridge 0000:01:00.0: Port 0: Link 0, Link Port 0 (TAB 1): DUAL DVB-S2 MAX
ddbridge 0000:01:00.0: Port 1: Link 0, Link Port 1 (TAB 2): DUAL DVB-S2 MAX
ddbridge 0000:01:00.0: Port 2: Link 0, Link Port 2 (TAB 3): DUAL DVB-S2 MAX
ddbridge 0000:01:00.0: Port 3: Link 0, Link Port 3 (TAB 4): DUAL DVB-S2 MAX
ddbridge 0000:01:00.0: Read mxl_fw from link 0
ddbridge 0000:01:00.0: Set fmode link 0 = 3
ddbridge 0000:01:00.0: DVB: registering adapter 0 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 1 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 2 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 3 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 4 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 5 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 6 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:01:00.0: DVB: registering adapter 7 frontend 0 (MaxLinear MxL5xx DVB-S/S2 tuner-demodulator)...
ddbridge 0000:03:00.0: enabling device (0100 -> 0102)
ddbridge 0000:03:00.0: detected Digital Devices Octopus Mini
ddbridge 0000:03:00.0: HW 0001000d REGMAP 00010004
ddbridge 0000:03:00.0: Port 0: DuoFlex CI 1.1
ddbridge 0000:03:00.0: Port 0: Link 0, Link Port 0 (TAB 1): DuoFlex CI
ddbridge 0000:03:00.0: Port 1: Link 0, Link Port 1 (TAB 2): DuoFlex CI_B
ddbridge 0000:03:00.0: Port 2: Link 0, Link Port 2 (TAB 3): NO MODULE
ddbridge 0000:03:00.0: Port 3: Link 0, Link Port 3 (TAB 4): NO MODULE
```

### Tail log for DVB & CA

```
~~~~~ snip snap ~~~~~
[08/09 13:04:22.349 AD0]: AD 0 [demux 0 0], setting filter on PID 6923 for fd 36
[08/09 13:04:22.349 AD0]: AD 0 [demux 0 0], setting filter on PID 6667 for fd 37
[08/09 13:04:22.349 AD0]: AD 0 [demux 0 0], setting filter on PID 7179 for fd 38
[08/09 13:04:22.349 AD0]: ddci_process_ts ro 0, wo 0 max 18800000
[08/09 13:04:22.349 AD0]: ddci_create_pat: transponder 12 version 1, len 17
[08/09 13:04:22.349 AD0]: ddci_replace_pi: CA pid 6923 -> pid 6923
[08/09 13:04:22.349 AD0]: ddci_replace_pi: CA pid 6667 -> pid 6667
[08/09 13:04:22.349 AD0]: ddci_replace_pi: CA pid 7179 -> pid 7179
[08/09 13:04:22.349 AD0]: ddci_create_pmt: PMT 1 AD 0, pid: 0062 (98), ver 1, pmt_len 80, pi_len 18, total_len 49, sid 006B (107)  
[08/09 13:04:22.349 AD0]: DDCI: PMT pid 98 - stream pid 767 -> 767 es_len 3, pos 0
[08/09 13:04:22.349 AD0]: DDCI: PMT pid 98 - stream pid 771 -> 771 es_len 16, pos 8
[08/09 13:04:22.349 AD0]: DDCI: PMT pid 98 - stream pid 772 -> 772 es_len 16, pos 29
[08/09 13:04:22.349 AD0]: writing 39104 bytes to DDCI device 9, fd 25, sock -1
```
[minisatip_dvb_ca.log](https://github.com/catalinii/minisatip/files/5187994/minisatip_dvb_ca.log)

### Core dump

```
~~~~~ snip snap ~~~~~
=================================================================
==10184==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f4ae3bf3b41 at pc 0x5589f9185b6a bp 0x7f4ae3bf2c70 sp 0x7f4ae3bf2c60
READ of size 1 at 0x7f4ae3bf3b41 thread T13
    #0 0x5589f9185b69 in set_pid_ts /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/ddci.c:503
    #1 0x5589f918b6c3 in ddci_process_ts /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/ddci.c:879
    #2 0x5589f918c02f in ddci_ts /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/ddci.c:919
    #3 0x5589f915cf0a in tables_ca_ts /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/tables.c:132
    #4 0x5589f91573f8 in pmt_process_stream /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/pmt.c:945
    #5 0x5589f91071c2 in process_dmx /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/stream.c:994
    #6 0x5589f91080ab in read_dmx /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/stream.c:1084
    #7 0x5589f90fbd17 in select_and_execute /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/socketworks.c:894
    #8 0x7f4aec39f3e8 in start_thread (/usr/lib/libpthread.so.0+0x93e8)
    #9 0x7f4aeb63b292 in __GI___clone (/usr/lib/libc.so.6+0x100292)

Address 0x7f4ae3bf3b41 is located in stack of thread T13 at offset 81 in frame
    #0 0x5589f918a94f in ddci_process_ts /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/ddci.c:813

  This frame has 4 object(s):
    [32, 36) 'ddci' (line 819)
    [48, 52) 'rewrite' (line 819)
    [64, 68) 'ad_pos' (line 882)
    [80, 6080) 'psi' (line 861) <== Memory access at offset 81 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T13 created by T0 here:
    #0 0x7f4aec4101c7 in __interceptor_pthread_create /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x5589f9121aa1 in start_new_thread /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/utils.c:1440
    #2 0x5589f9117f73 in init_hw /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/adapter.c:352
    #3 0x5589f9118cad in get_free_adapter /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/adapter.c:746
    #4 0x5589f90fee3c in start_play /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/stream.c:297
    #5 0x5589f90ec689 in read_rtsp /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/minisatip.c:1247
    #6 0x5589f90fbd17 in select_and_execute /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/socketworks.c:894
    #7 0x5589f90e65ba in main /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/minisatip.c:1869
    #8 0x7f4aeb563151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)

SUMMARY: AddressSanitizer: stack-use-after-scope /home/supervisor/aur/minisatip-git-ddci/src/minisatip/src/ddci.c:503 in set_pid_ts
Shadow bytes around the buggy address:
  0x0fe9dc776710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9dc776720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9dc776730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 cb cb
  0x0fe9dc776740: cb cb cb cb 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9dc776750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
=>0x0fe9dc776760: f1 f1 04 f2 04 f2 04 f2[f8]f8 f8 f8 f8 f8 f8 f8
  0x0fe9dc776770: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0fe9dc776780: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0fe9dc776790: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0fe9dc7767a0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0fe9dc7767b0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==10184==ABORTING
```
[minisatip_core_dump.log](https://github.com/catalinii/minisatip/files/5187939/minisatip_core_dump.log)

### May help
```
# systool -vm ddbridge
Module = "ddbridge"

  Attributes:
    coresize            = "98304"
    initsize            = "0"
    initstate           = "live"
    refcnt              = "0"
    srcversion          = "DE2AFC5D10414FAE869B16C"
    taint               = ""
    uevent              = <store method only>
    version             = "0.9.33-integrated"

  Parameters:
    adapter_alloc       = "0"
    adapter_nr          = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"
    alt_dma             = "0"
    ci_bitrate          = "70000"
    dma_buf_num         = "8"
    dma_buf_size        = "21"
    dummy_tuner         = "0"
    fmode               = "3"
    fmode_sat           = "-1"
    msi                 = "0"
    no_init             = "0"
    old_quattro         = "0"
    stv0910_single      = "0"
    ts_loop             = "-1"
    xo2_speed           = "2"

  Sections:
    .bss                = "0xffffffffc105c440"
    .data.once          = "0xffffffffc105c078"
    .data               = "0xffffffffc105b000"
    .exit.text          = "0xffffffffc1053fa1"
    .gnu.linkonce.this_module= "0xffffffffc105c080"
    .init.text          = "0xffffffffc15df000"
    .note.Linux         = "0xffffffffc1054024"
    .note.gnu.build-id  = "0xffffffffc1054000"
    .orc_unwind         = "0xffffffffc1057f70"
    .orc_unwind_ip      = "0xffffffffc1056c90"
    .rodata             = "0xffffffffc1054040"
    .rodata.str1.1      = "0xffffffffc1055558"
    .rodata.str1.8      = "0xffffffffc1056040"
    .strtab             = "0xffffffffc15e3090"
    .symtab             = "0xffffffffc15e0000"
    .text               = "0xffffffffc1049000"
    .text.unlikely      = "0xffffffffc1052c28"
    __bug_table         = "0xffffffffc105bdb0"
    __jump_table        = "0xffffffffc105a000"
    __mcount_loc        = "0xffffffffc10550f0"
    __param             = "0xffffffffc1056a38"
    __verbose           = "0xffffffffc105bdd8"
```

**Comment by catalinii** [comment]
Can you check now ?
