### ISSUE TITLE
sat vertical pos issue, log typos

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#78]
dvb.c:854 tp->pol is integer so char from the url is handled wrong

we may can do it like
  tp->pol = toupper (arg[i][4] ) == 'V' ? 0 : 1;

so there is something, and I'm not able to tune to a vertical channel

adapter.c:293 pol is int  and in LOG %c
adapter.c:554 needs to be 0 or 1 tp->pol
adapter.c:657 pol needs to be a char    t->pol ? 'H':'V'

dvb.c:900
pltf should be plts

I did sent you a diff 

I did look at the SES spec and there is also l and r for pol=

Set to one of the following values: "h" horizontal linear,
"v" vertical linear, "l" circular left,
"r" circular right.

**Comment by catalinii** [comment]
Hi,

I rework a good part of dvb.c and removed some duplicates in order to make easy adding additional delivery systems.

This will be in the next commit.

**Comment by catalinii** [comment]
This should be fixed now

**Comment by 9000h** [comment]
yes vert/hor works now but when I try a channel scan it dumps a core
please note also the unusual string fragments in the log

RTSP/1.0 200 OK
Cseq: 22
Date: Tue, Feb 3 17:23:54 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?addpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040;seq=0


[03/02 18:23:54.464]: bandwidth 2KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[03/02 18:23:54.661]: read RTSP (from handle 18 sock_id 6, ts: 44418, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?delpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040 RTSP/1.0
CSeq: 23
Session: 1804289383

alive
[03/02 18:23:54.661]: starting init_hw 1
[03/02 18:23:54.661]: detect_dvb_parameters (S)-> delpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040
[03/02 18:23:54.661]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=NULL - dpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040
[03/02 18:23:54.661]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:54.661]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:54.661]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040
[03/02 18:23:54.661]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:54.661]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:54.661]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=1024, dpids=NULL
[03/02 18:23:54.661]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040
[03/02 18:23:54.661]: deleting pids on adapter 2, sid 0, pids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040
[03/02 18:23:54.661]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:54.661]: clearing filters on PID 1024 FD 20
[03/02 18:23:54.661]: clearing filters on PID 1025 FD 21
[03/02 18:23:54.661]: clearing filters on PID 1026 FD 22
[03/02 18:23:54.661]: clearing filters on PID 1027 FD 23
[03/02 18:23:54.661]: clearing filters on PID 1029 FD 24
[03/02 18:23:54.661]: clearing filters on PID 1035 FD 25
[03/02 18:23:54.661]: clearing filters on PID 1030 FD 26
[03/02 18:23:54.661]: clearing filters on PID 1031 FD 27
[03/02 18:23:54.661]: clearing filters on PID 1032 FD 28
[03/02 18:23:54.661]: clearing filters on PID 1036 FD 29
[03/02 18:23:54.661]: clearing filters on PID 1038 FD 30
[03/02 18:23:54.661]: clearing filters on PID 1033 FD 31
[03/02 18:23:54.661]: clearing filters on PID 1028 FD 32
[03/02 18:23:54.661]: clearing filters on PID 1037 FD 33
[03/02 18:23:54.661]: clearing filters on PID 1039 FD 34
[03/02 18:23:54.661]: clearing filters on PID 1040 FD 35
[03/02 18:23:54.661]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 23
Date: Tue, Feb 3 17:23:54 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?delpids=1024,1025,1026,1027,1029,1035,1030,1031,1032,1036,1038,1033,1028,1037,1039,1040;seq=0


[03/02 18:23:54.663]: read RTSP (from handle 18 sock_id 6, ts: 44661, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?addpids=1043,1044,1045,17 RTSP/1.0
CSeq: 24
Session: 1804289383

028,1037,1039,1040
[03/02 18:23:54.663]: starting init_hw 1
[03/02 18:23:54.663]: detect_dvb_parameters (S)-> addpids=1043,1044,1045,17
[03/02 18:23:54.663]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=1043,1044,1045,17 - dpids=NULL
[03/02 18:23:54.663]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:54.663]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:54.663]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=1043,1044,1045,17, dpids=NULL
[03/02 18:23:54.663]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:54.663]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:54.663]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1024
[03/02 18:23:54.663]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=1043,1044,1045,17, dpids=NULL
[03/02 18:23:54.663]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:54.663]: setting filter on PID 1043 for fd 20
[03/02 18:23:54.663]: setting filter on PID 1044 for fd 21
[03/02 18:23:54.663]: setting filter on PID 1045 for fd 22
[03/02 18:23:54.663]: setting filter on PID 17 for fd 23
[03/02 18:23:54.663]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 24
Date: Tue, Feb 3 17:23:54 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?addpids=1043,1044,1045,17;seq=0


[03/02 18:23:55.191]: read RTSP (from handle 18 sock_id 6, ts: 44663, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?delpids=1043,1044,1045,17 RTSP/1.0
CSeq: 25
Session: 1804289383

028,1037,1039,1040
[03/02 18:23:55.191]: starting init_hw 1
[03/02 18:23:55.191]: detect_dvb_parameters (S)-> delpids=1043,1044,1045,17
[03/02 18:23:55.191]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=NULL - dpids=1043,1044,1045,17
[03/02 18:23:55.191]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:55.191]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:55.191]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1043,1044,1045,17
[03/02 18:23:55.191]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:55.191]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:55.191]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=1043, dpids=NULL
[03/02 18:23:55.191]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1043,1044,1045,17
[03/02 18:23:55.191]: deleting pids on adapter 2, sid 0, pids=1043,1044,1045,17
[03/02 18:23:55.191]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:55.191]: clearing filters on PID 1043 FD 20
[03/02 18:23:55.191]: clearing filters on PID 1044 FD 21
[03/02 18:23:55.191]: clearing filters on PID 1045 FD 22
[03/02 18:23:55.191]: clearing filters on PID 17 FD 23
[03/02 18:23:55.191]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 25
Date: Tue, Feb 3 17:23:55 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?delpids=1043,1044,1045,17;seq=0


[03/02 18:23:55.193]: read RTSP (from handle 18 sock_id 6, ts: 45191, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?addpids=17 RTSP/1.0
CSeq: 26
Session: 1804289383


[03/02 18:23:55.193]: starting init_hw 1
[03/02 18:23:55.193]: detect_dvb_parameters (S)-> addpids=17
[03/02 18:23:55.193]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=17 - dpids=NULL
[03/02 18:23:55.193]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:55.193]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:55.193]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=17, dpids=NULL
[03/02 18:23:55.193]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:55.193]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:55.193]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=1043
[03/02 18:23:55.193]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=17, dpids=NULL
[03/02 18:23:55.193]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:55.193]: setting filter on PID 17 for fd 20
[03/02 18:23:55.193]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 26
Date: Tue, Feb 3 17:23:55 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?addpids=17;seq=0


[03/02 18:23:55.557]: bandwidth 18KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[03/02 18:23:56.091]: get_signal took 32 ms for adapter 2 handle 15 (status: 31, ber: 0, strength:5642, snr: 10775, max_strength: 5642, max_snr: 42942)
[03/02 18:23:56.560]: bandwidth 15KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[03/02 18:23:56.625]: read RTSP (from handle 18 sock_id 6, ts: 45193, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?delpids=17 RTSP/1.0
CSeq: 27
Session: 1804289383


[03/02 18:23:56.625]: starting init_hw 1
[03/02 18:23:56.625]: detect_dvb_parameters (S)-> delpids=17
[03/02 18:23:56.625]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=NULL - dpids=17
[03/02 18:23:56.625]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:56.625]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:56.626]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=17
[03/02 18:23:56.626]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:56.626]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:56.626]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=17, dpids=NULL
[03/02 18:23:56.626]: copy_dvb_parameters -> src=1, fe=0, freq=10788000, fec=5 sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=17
[03/02 18:23:56.626]: deleting pids on adapter 2, sid 0, pids=17
[03/02 18:23:56.626]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:56.626]: clearing filters on PID 17 FD 20
[03/02 18:23:56.626]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 27
Date: Tue, Feb 3 17:23:56 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?delpids=17;seq=0


[03/02 18:23:56.633]: read RTSP (from handle 18 sock_id 6, ts: 46625, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?src=1&freq=10803&msys=dvbs2&plts=on&fec=34&pol=h&ro=0.35&sr=22000&mtype=8psk&pids=0 RTSP/1.0
CSeq: 28
Session: 1804289383


[03/02 18:23:56.633]: starting init_hw 1
[03/02 18:23:56.633]: detect_dvb_parameters (S)-> src=1&freq=10803&msys=dvbs2&plts=on&fec=34&pol=h&ro=0.35&sr=22000&mtype=8psk&pids=0
[03/02 18:23:56.633]: detect_dvb_parameters (E) -> src=1, fe=0, freq=10803000, fec=3, sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=0 - apids=NULL - dpids=NULL
[03/02 18:23:56.633]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:56.633]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:56.633]: copy_dvb_parameters -> src=1, fe=0, freq=10803000, fec=3 sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=0, apids=NULL, dpids=NULL
[03/02 18:23:56.633]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:56.633]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10788000
[03/02 18:23:56.633]: deleting pids on adapter 2, sid -1, pids=NULL
[03/02 18:23:56.633]: deleting pids on adapter 2, sid -1, pids=NULL
[03/02 18:23:56.634]: copy_dvb_param start -> src=1, fe=0, freq=10788000, fec=5, sr=22000000, pol=1, ro=0, msys=5, mtype=0, plts=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=17
[03/02 18:23:56.634]: copy_dvb_parameters -> src=1, fe=0, freq=10803000, fec=3 sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=0, apids=NULL, dpids=NULL
[03/02 18:23:57.978]: tunning to 10803000(1053000) pol: h (1) sr:22000000 fec:34 delsys:dvbs2 mod:8psk rolloff:0.35 pilot:on
[03/02 18:23:57.978]: setting filter on PID 0 for fd 20
[03/02 18:23:57.978]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 28
Date: Tue, Feb 3 17:23:57 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?src=1;seq=0


[03/02 18:23:57.579]: no data sent for more than 1s sid: 0 for 192.168.178.112:52012
[03/02 18:23:57.594]: bandwidth 9KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[03/02 18:23:57.694]: read RTSP (from handle 18 sock_id 6, ts: 46633, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?delpids=0 RTSP/1.0
CSeq: 29
Session: 1804289383

.35
[03/02 18:23:57.694]: starting init_hw 1
[03/02 18:23:57.694]: detect_dvb_parameters (S)-> delpids=0
[03/02 18:23:57.694]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=NULL - dpids=0
[03/02 18:23:57.694]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:57.694]: copy_dvb_param start -> src=1, fe=0, freq=10803000, fec=3, sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:57.694]: copy_dvb_parameters -> src=1, fe=0, freq=10803000, fec=3 sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=0
[03/02 18:23:57.694]: Play for stream 0, type 2, rsock 19, adapter 2, sock_id 6 handle 18
[03/02 18:23:57.694]: setting DVB parameters for adapter 2 - master_sid 0 sid 0 old f:10803000
[03/02 18:23:57.694]: copy_dvb_param start -> src=1, fe=0, freq=10803000, fec=3, sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=0, apids=NULL, dpids=NULL
[03/02 18:23:57.694]: copy_dvb_parameters -> src=1, fe=0, freq=10803000, fec=3 sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=0
[03/02 18:23:57.694]: deleting pids on adapter 2, sid 0, pids=0
[03/02 18:23:57.695]: not tunning for SID 0 (do_tune=0, master_sid=0)
[03/02 18:23:57.695]: clearing filters on PID 0 FD 20
[03/02 18:23:57.695]: reply -> 18 (192.168.178.112:49231) CL:0 :
RTSP/1.0 200 OK
Cseq: 29
Date: Tue, Feb 3 17:23:57 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=52012-52013;server_port=49899-49900
Session: 1804289383;timeout=30
com.ses.streamID: 1
RTP-Info: url=rtsp://192.168.178.133:554/stream=1?delpids=0;seq=0


[03/02 18:23:57.697]: read RTSP (from handle 18 sock_id 6, ts: 47694, len: 0):
PLAY rtsp://192.168.178.133:554/stream=1?addpids=96,97,98,99,100,101,115,129,130,131,144,17 RTSP/1.0
CSeq: 30
Session: 1804289383

CSeq:
[03/02 18:23:57.698]: starting init_hw 1
[03/02 18:23:57.698]: detect_dvb_parameters (S)-> addpids=96,97,98,99,100,101,115,129,130,131,144,17
[03/02 18:23:57.698]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=96,97,98,99,100,101,115,129,130,131,144,17 - dpids=NULL
[03/02 18:23:57.698]: Setup stream 0 parameters, sock_id 6, handle 18
[03/02 18:23:57.698]: copy_dvb_param start -> src=1, fe=0, freq=10803000, fec=3, sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[03/02 18:23:57.698]: copy_dvb_parameters -> src=1, fe=0, freq=10803000, fec=3 sr=22000000, pol=2, ro=0, msys=6, mtype=9, plts=0, bw=8000000, inv=2, pids=NULL, apids=96,97,98,99,100,101,115,129,130,131,144,17, dpids=NULL

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7632784 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7632784 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff762f690 in atoi () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000403b22 in read_rtsp (s=0x61d060) at minisatip.c:457
#3  0x0000000000407a5b in select_and_execute () at socketworks.c:409
#4  0x0000000000405853 in main (argc=6, argv=0x7fffffffe6a8) at minisatip.c:848
(gdb)
(gdb) print s
$1 = {{sock = 7, sa = {sin_family = 2, sin_port = 24549, sin_addr = {
        s_addr = 2058528960}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x405089 <ssdp_reply>, close = 0, timeout = 0x404e06 <ssdp_discovery>, 
    type = 0, sid = -1, rtime = 30431, buf = 0x7fffffffdd40 "PLAY", lbuf = 2000, 
    rlen = 345, close_sec = 1800000, sock_id = 0, err = 0, flags = 0}, {sock = 8, 
    sa = {sin_family = 2, sin_port = 24549, sin_addr = {s_addr = 2058528960}, 
      sin_zero = "\000\000\000\000\000\000\000"}, action = 0x405089 <ssdp_reply>, 
    close = 0, timeout = 0x404e06 <ssdp_discovery>, type = 0, sid = -1, 
    rtime = 30431, buf = 0x7fffffffdd40 "PLAY", lbuf = 2000, rlen = 345, 
    close_sec = 0, sock_id = 1, err = 0, flags = 0}, {sock = 9, sa = {sin_family = 0, 
      sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, action = 0x40528d <new_rtsp>, 
    close = 0, timeout = 0x404d2d <close_http>, type = 2, sid = -1, rtime = 19190, 
    buf = 0x7fffffffdd40 "PLAY", lbuf = 2000, rlen = 0, close_sec = 0, sock_id = 2, 
    err = 0, flags = 0}, {sock = 10, sa = {sin_family = 0, sin_port = 0, sin_addr = {
        s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x4052c5 <new_http>, close = 0, timeout = 0x404d2d <close_http>, 
    type = 2, sid = -1, rtime = 792, buf = 0x7fffffffdd40 "PLAY", lbuf = 2000, 
    rlen = 0, close_sec = 0, sock_id = 3, err = 0, flags = 0}, {sock = 14, sa = {
      sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, action = 0x40b037 <read_dmx>, 
    close = 0x40f4fc <close_adapter_for_socket>, timeout = 0, type = 5, sid = 1, 
    rtime = 532, buf = 0x62ecb0 "", lbuf = 9212, rlen = 0, close_sec = 60000, 
---Type <return> to continue, or q <return> to quit---
    sock_id = 4, err = 0, flags = 0}, {sock = 16, sa = {sin_family = 0, sin_port = 0, 
      sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x40b037 <read_dmx>, close = 0x40f4fc <close_adapter_for_socket>, 
    timeout = 0, type = 5, sid = 2, rtime = 47691, buf = 0x6310c0 "G@", lbuf = 9212, 
    rlen = 0, close_sec = 60000, sock_id = 5, err = 0, flags = 0}, {sock = 18, sa = {
      sin_family = 2, sin_port = 20416, sin_addr = {s_addr = 1890756800}, 
      sin_zero = "\000\000\000\000\000\000\000"}, action = 0x4035b7 <read_rtsp>, 
    close = 0x404d2d <close_http>, timeout = 0x40bce0 <stream_timeout>, type = 4, 
    sid = 0, rtime = 47694, buf = 0x7fffffffdd40 "PLAY", lbuf = 2000, rlen = 0, 
    close_sec = 200, sock_id = 6, err = 0, flags = 0}, {sock = -1, sa = {
      sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, action = 0, close = 0, timeout = 0, 
    type = 0, sid = 0, rtime = 0, buf = 0x0, lbuf = 0, rlen = 0, close_sec = 0, 
    sock_id = 0, err = 0, flags = 0} <repeats 93 times>}
(gdb)

**Comment by catalinii** [comment]
last commit should fix this :)

**Comment by catalinii** [comment]
Can you test ?

Thanks

**Comment by 9000h** [comment]
look like the core dump is fixed, a scan with DD-TV on Astra 19.2 did find 1321 channels
als the android Tivizen satip app (I know it's not made for Astra 19.2) did find some channels more as the same scan on the digibit r1
