### ISSUE TITLE
minisatip crash

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#849]
try to reproduce, but seem to come from the last commit
```
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: closed stream sid 0
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: minisatip.c:1954 get_sid returns NULL for s_id = -1
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: Reply (handle 7) [192.168.178.153:17263] content_len:0, sock 7
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: MSG client << process :
May 24 23:43:35 localhost minisatip[10930]: RTSP/1.0 200 OK
May 24 23:43:35 localhost minisatip[10930]: Date: Mon, May 24 21:43:35 2021 GMT
May 24 23:43:35 localhost minisatip[10930]: CSeq: 16
May 24 23:43:35 localhost minisatip[10930]: Server: minisatip/v1.1.5-df9d5a4
May 24 23:43:35 localhost minisatip[10930]: Session: 1914544919
May 24 23:43:35 localhost minisatip[10930]: #015
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: socketworks.c:502 Unlock disabled mutex 0x55a88ffa5f88
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.605 main]: sockets_unlock: Changing socket 7 lock 0x55a88ffa5f88 to NULL error -1 Success
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: minisatip.c:1096 get_sid returns NULL for s_id = -1
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: Read RTSP (sock 7, handle 7) [192.168.178.153:17263] sid -1, len: 0
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: MSG client >> process :
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: Most likely not an RTSP packet sock_id: 7 sid: -1 rlen: 0, dropping ....
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: select_and_execute[7]: Close on socket 7 (sid:-1) from 192.168.178.153:17263 - type rtsp (4) errno 0
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: minisatip.c:1544 get_sid returns NULL for s_id = -1
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: Requested sid close -1 timeout -1 type -1, sock 7, handle 7, timeout 0
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: closing stream sid -1
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: sockets_del: sock 7 -> handle 7, sid -1, overflow bytes 0, allocated 0, used 0, unsend packets 0
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: sockets_del: sock 7 Last open socket is at index 12 current_handle 7
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: Destroying mutex 0x55a88ff95c48
May 24 23:43:35 localhost minisatip[10930]: [24/05 23:43:35.611 main]: Delete socket 7 done: sid -1
May 24 23:43:36 localhost minisatip[10930]: [24/05 23:43:36.433 signal]: BW 252KB/s, Total BW: 1111 MB, ns/read 1335, r: 4, w: 6 fw: 0, tt: 5 ms
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: Requested adapter 0 close due to timeout 30 sec, result 1 max_rtime 187720957
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: closing DVR socket 11 pos 11 aid 0
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: closing adapter 0  -> fe:10 dvr:11, sock:11, fe_sock:-1
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: deleting pids on adapter 0, sid -1, pids=NULL
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: Destroying mutex 0x55a88ff9d0a8
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: done closing adapter 0
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.655 AD0]: sockets_del: sock 11 -> handle 11, sid -1, overflow bytes 0, allocated 0, used 0, unsend packets 0
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.656 AD0]: sockets_del: sock 11 Last open socket is at index 12 current_handle 11
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.656 AD0]: Destroying mutex 0x55a88ffa5248
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.756 AD0]: No enabled sockets for Thread ID 7f552ffff700 name AD0 ... exiting
May 24 23:44:05 localhost minisatip[10930]: [24/05 23:44:05.756 AD0]: add_join_thread: pthread 7f552ffff700
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.158 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.158 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.158 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.158 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.158 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.159 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
May 24 23:44:06 localhost minisatip[10930]: [24/05 23:44:06.160 main]: requested dvbapi close for sock 12, sock_id 19
May 24 23:44:06 localhost minisatip[10930]: ?? ??:0
May 24 23:44:06 localhost minisatip[10930]: message repeated 9 times: [ ?? ??:0]
May 24 23:44:06 localhost minisatip[10930]: RECEIVED SIGNAL 11 - SP=0 IP=0
May 24 23:44:06 localhost minisatip[10930]: Obtained 10 stack frames.
May 24 23:44:06 localhost minisatip[10930]: 0x55a88e719999 : 0x55a88e719a8e : 0x7f55547cc980 : 0x55a88e71da61 : 0x55a88e723b9c : 0x55a88e72299a : 0x55a88e704a12 : 0x55a88e720496 : 0x55a88e723d1a : 0x55a88e72299a :
May 24 23:44:06 localhost systemd[1]: minisatip.service: Main process exited, code=exited, status=1/FAILURE
May 24 23:44:06 localhost systemd[1]: minisatip.service: Failed with result 'exit-code'.

```

**Comment by catalinii** [comment]
Can you compile with: make debug 
and then try to reproduce ?

**Comment by 9000h** [comment]
Will try when back from abroad

**Comment by 9000h** [comment]
ok could replicate the issue, when you play an encrypted channel and you stop oscam then minisatip will cash

**Comment by 9000h** [comment]
```
[24/06 09:45:49.764 main]: write to dvbapi socket failed (-1 out of 8), closing socket -1, errno 9, error: Bad file descriptor
[24/06 09:45:49.764 main]: requested dvbapi close for sock 10, sock_id 16

Thread 1 "minisatip" received signal SIGSEGV, Segmentation fault.
0x000055555557dc98 in mutex_lock1 (FILE=0x5555555bb98e "dvbapi.c", 
    line=759, mutex=0x5555557d2f40 <keys_mutex>) at utils.c:1270
1270	    mutexes[imtx++] = mutex;
(gdb) bt
#0  0x000055555557dc98 in mutex_lock1 (FILE=0x5555555bb98e "dvbapi.c", 
    line=759, mutex=0x5555557d2f40 <keys_mutex>) at utils.c:1270
#1  0x0000555555583e9b in keys_del (i=0) at dvbapi.c:759
#2  0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#3  0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#4  0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#5  0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#6  0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#7  0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#8  0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#9  0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#10 0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#11 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
---Type <return> to continue, or q <return> to quit---
#12 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#13 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#14 0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#15 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#16 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#17 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#18 0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#19 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#20 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#21 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#22 0x0000555555582bad in dvbapi_close (s=0x55555582c390)
    at dvbapi.c:497
#23 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#24 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
---Type <return> to continue, or q <return> to quit---
#25 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#26 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#27 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#28 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#29 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#30 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#31 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#32 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#33 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#34 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#35 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#36 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#37 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#38 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#39 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#40 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#41 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#42 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#43 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#44 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#45 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#46 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#47 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#48 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#49 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#50 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#51 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#52 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#53 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#54 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#55 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#56 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#57 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#58 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#59 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#60 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#61 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#62 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#63 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#64 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#65 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#66 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#67 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#68 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#69 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#70 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#71 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#72 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#73 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#74 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#75 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#76 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#77 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
---Type <return> to continue, or q <return> to quit---
#78 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#79 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#80 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#81 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#82 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#83 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#84 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#85 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#86 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#87 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#88 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#89 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#90 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#91 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#92 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#93 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#94 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#95 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#96 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#97 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#98 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#99 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#100 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#101 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#102 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#103 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#104 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#105 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#106 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#107 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#108 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#109 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#110 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#111 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#112 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#113 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#114 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#115 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#116 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#117 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#118 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#119 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#120 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#121 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#122 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#123 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#124 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#125 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#126 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#127 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#128 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#129 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#130 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
---Type <return> to continue, or q <return> to quit---
#131 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#132 0x00005555555806cd in dvbapi_close_socket () at dvbapi.c:88
#133 0x0000555555583f2d in keys_del (i=0) at dvbapi.c:759
#134 0x0000555555582bad in dvbapi_close (s=0x55555582c390) at dvbapi.c:497
#135 0x0000555555564c35 in sockets_del (sock=10) at socketworks.c:607
#136 0x00005555555660c9 in select_and_execute (arg=0x0) at socketworks.c:888
#137 0x0000555555561959 in main (argc=16, argv=0x7fffffffe348) at minisatip.c:1894
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) print mutex
$1 = (SMutex *) 0x5555557d2f40 <keys_mutex>
(gdb) print $mutex
$2 = void
(gdb) print *mutex
$3 = {enabled = 1, mtx = pthread_mutex_t = {Type = Recursive, Status = Acquired, possibly with no waiters, Owner ID = 14186, Robust = No, Shared = No, Protocol = None, Times acquired by the owner = 34}, 
  state = 34, line = 759, tid = 140737353922048, lock_time = 100132, create_time = 2, file = 0x5555555bb98e "dvbapi.c"}
(gdb) print mutexes[imtx++]
Cannot access memory at address 0x7ffe581a7918
(gdb) 
```

**Comment by 9000h** [comment]
fixed by https://github.com/catalinii/minisatip/pull/871
